FROM alpine:3.23

ARG TARGETARCH

RUN apk add --no-cache \
        squashfs-tools \
        grub \
        grub-efi \
        mtools \
        xorriso \
    && if [ "$TARGETARCH" = "amd64" ]; then apk add --no-cache grub-bios; fi
