name: Deploy Image

on:
  push:
    branches: [ "26" ]
  schedule:
    - cron: '0 0 */14 * *'

jobs:
  call-docker-publish:
    uses: ./.github/workflows/reusable.yml
    with:
      dockerfile: fedora/Containerfile