name: Deploy Image

on:
  push:
    branches: [ "tanit" ]
  schedule:
    - cron: '0 0 */14 * *'

permissions:
  contents: read
  packages: write

jobs:
  call-docker-publish:
    uses: ./.github/workflows/reusable.yml
    with:
      dockerfile: xorriso/Containerfile
      name: "xorriso"